name: nbu_rates
description: A Flutter app for watching NBU rates.

# https://dart.dev/tools/pub/pubspec
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
      sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Modular for navigation and DI
  flutter_modular: ^5.0.0

  # Bloc for state management
  flutter_bloc: ^8.0.0

  # SharedPreferences for local storage
  shared_preferences: ^2.2.3

  # EasyLocalization for localization
  easy_localization: ^3.0.7

  #Dio for network
  dio: ^5.0.2

  #ConnectivityPlus for check internet connection
  connectivity_plus: ^3.0.3

  #Equatable for State objects
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
